### ISSUE TITLE
[New Devices]ESP32 C3 C2 support

### ISSUE THREAD

**Issue by JamesJian-tech** [Azure/embedded-wireless-framework#1]
Hi 

Any change to add ESP32 C3 and C2 AT Firmware ?

Cheers

J J

**Comment by andrejm-rtos** [comment]
We talking with Espressif, ESP support is planned for the near future.

**Comment by andrejm-rtos** [comment]
Examples for a few Espressif adapters is now available. We are still working on them, more feature on the way.

**Comment by JamesJian-tech** [comment]
THanks
