### ISSUE TITLE
Renesas RYZ014A Modem API Return Values

### ISSUE THREAD

**Issue by renesas-adam-benson** [Azure/embedded-wireless-framework#10]
The APIs in `ewf_adapter_api_modem_general.c` return the entire AT command response instead of parsing it. Is this intended functionality or will these APIs parse the commands in the future? 

For example the return for `ewf_adapter_modem_manufacturer_read` would be: `\r\nRenesas\0\n\r\n\0K\r\n`.

**Comment by andresmlinar** [comment]
The commands as of today return full responses. It is left to the user of the API to parse. We are working in a new parser that you can optionally use in your implementation. This will be released as an option, to keep compatibility. Plan for this is before February 2023.
