### ISSUE TITLE
How do I send telemetry data to azure iot central?

### ISSUE THREAD

**Issue by busratuzcu** [Azure/embedded-wireless-framework#5]
I try to connect Azure iot central using sim7000e and stm32h4. First, I created a new device on azure iot central. I scanned embedded wireless framework examples but I couldn't find any example about sim7000e connection. How to send telemetry to azure iot central using sim7000e? Is there any sample?

**Comment by andresmlinar** [comment]
We are working on SIMcom drivers and examples, we plan to push them to GitHub in January 2023. 

For IoT Central we have examples for WIN32 that show how to use EWF with IoT Central. Look for the examples that contain _azure_iot_provisioning_ and _azure_iot_pnp_provisioning_ on the name.

**Comment by andrejm-rtos** [comment]
The plan changes, not further effort on SIMcom drivers is planned. You can use the WIN32 examples with IoT central as a base to adapt the code to your needs.
