### ISSUE TITLE
SIM7000 or SIM7600 example needed!

### ISSUE THREAD

**Issue by umtkyck** [Azure/embedded-wireless-framework#6]
I am testing my sim7000e module with stm32 but couldn't find any appropriate example. Could you pls help me to find it??

**Comment by andresmlinar** [comment]
We are working on them. We plan to release drivers and examples in January 2023.

**Comment by iliaschat** [comment]
Hello. 
@andresmlinar Are there any updates regarding examples?
@umtkyck did you make it work?

**Comment by umtkyck** [comment]
Put your keyboard slowly to the desk and run away from ewf. They will not help you.

**Comment by andrejm-rtos** [comment]
@iliDaedalus @umtkyck the plan changed, currently SIM7000+STM32 is not scheduled, if you have a concrete project please get in touch with us

**Comment by MIKHANYA** [comment]
Need SIM7000G and ESP32 Example, Please
