### ISSUE TITLE
Renesas RYZ014A Linker Issues

### ISSUE THREAD

**Issue by renesas-adam-benson** [Azure/embedded-wireless-framework#9]
Certain API's that aren't implemented for the RYZ014A will return a linker error if the user attempts to call them in an application. For example:

- `Error[Li005]: no definition for "ewf_adapter_modem_timezone_autoupdate_set"`
- `Error[Li005]: no definition for "ewf_adapter_modem_signal_strength_read"`
- `Error[Li005]: no definition for "ewf_adapter_modem_signal_strength_extended_read"`
- `Error[Li005]: no definition for "ewf_adapter_modem_clock_read"`

Would it be possible for these and other unimplemented APIs for the RYZ to return `EWF_RESULT_NOT_SUPPORTED` until they are fully implemented?

**Comment by andresmlinar** [comment]
We are updating the drivers with the missing functionality. We plan to push the changes to GitHub on January 2023.

**Comment by andrejm-rtos** [comment]
There is no plan to add these. You can modify the code to fit your needs.
